spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
    generate-ddl: true
    hibernate:
      ddl-auto: update
  daniel:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://mariadb:3306/daniel
      username: hyungeun
      password: jesusinlove0123
  h2:
    console:
      enabled: true
  elasticsearch:
    url: elasticsearch
    port: 9200
  security:
    client:
      id: daniel-spring-boot
      secret: jesusinlove
logging:
  level:
    net.freehongs.daniel: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

