spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: create
    generate-ddl: true
    hibernate:
      ddl-auto: create
  daniel:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      #jdbc-url: jdbc:h2:tcp://localhost/~/daniel
      jdbc-url: jdbc:mariadb://localhost:3306/daniel
      username: hyungeun
      password: qwer123$
  h2:
    console:
      enabled: true
  elasticsearch:
    url: localhost
    port: 9200
logging:
  level:
    net.freehongs.daniel: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

