spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: create    # 절대 변경 금지!
    generate-ddl: true
    hibernate:
      ddl-auto: create
  daniel:
    datasource:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/daniel
      username: sa
      password:
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

